# Generated by Django 5.0 on 2023-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='added',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='published',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='added_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='published_string',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
