# Generated by Django 5.0 on 2023-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_datamodel_added_remove_datamodel_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='insight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='intensity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='likelihood',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='pestle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
