# Generated by Django 5.0 on 2023-12-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_datamodel_country_alter_datamodel_insight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='title',
            field=models.CharField(blank=True, max_length=455),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
