# Generated by Django 5.0 on 2023-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_datamodel_title_alter_datamodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
